Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -62,6 +62,7 @@ jobs:
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -p ${{ secrets.SSH_HOST1_PORT }} ${{ secrets.HOST1 }} >> ~/.ssh/known_hosts
+        ssh-keyscan -p ${{ secrets.SSH_HOST2_PORT }} ${{ secrets.HOST2 }} >> ~/.ssh/known_hosts
         echo "SSH configuration complete on Runner."
 
     - name: Deploy using remote script
@@ -83,21 +84,21 @@ jobs:
         
         # 1. 쉘 스크립트를 원격 서버로 전송
         scp -P $SSH_HOST1_PORT "$DEPLOY_SCRIPT_PATH" $USERNAME@$HOST1:$REMOTE_SCRIPT_PATH
-        if [ $? -ne 0 ]; then echo "Error: Failed to transfer deploy script"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Failed to transfer deploy script from host1"; exit 1; fi
         scp -P $SSH_HOST2_PORT "$DEPLOY_SCRIPT_PATH" $USERNAME@$HOST2:$REMOTE_SCRIPT_PATH
-        if [ $? -ne 0 ]; then echo "Error: Failed to transfer deploy script"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Failed to transfer deploy script from host2"; exit 1; fi
 
         # 2. JAR 파일을 원격 서버로 전송
         scp -P $SSH_HOST1_PORT "./spring-boot-jar/$JAR_FILENAME" $USERNAME@$HOST1:$DEPLOY_PATH/$JAR_FILENAME
-        if [ $? -ne 0 ]; then echo "Error: Failed to transfer JAR file"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Failed to transfer JAR file from host1"; exit 1; fi
         scp -P $SSH_HOST2_PORT "./spring-boot-jar/$JAR_FILENAME" $USERNAME@$HOST2:$DEPLOY_PATH/$JAR_FILENAME
-        if [ $? -ne 0 ]; then echo "Error: Failed to transfer JAR file"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Failed to transfer JAR file from host2"; exit 1; fi
 
-        echo "--- DEPLOY JOB: Executing deploy script on remote server ---"
         # 3. 원격 서버에서 쉘 스크립트 실행 (인자 전달)
+        echo "--- DEPLOY JOB: Executing deploy script on remote server ---"
         ssh -p $SSH_HOST1_PORT $USERNAME@$HOST1 "bash \"$REMOTE_SCRIPT_PATH\" \"$DEPLOY_PATH\" \"$JAR_FILENAME\" \"${{ secrets.DB_URL }}\" \"${{ secrets.DB_USERNAME }}\" \"${{ secrets.DB_PASSWORD }}\""
-        if [ $? -ne 0 ]; then echo "Error: Remote deploy script failed"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Remote deploy script failed from host1"; exit 1; fi
         ssh -p $SSH_HOST2_PORT $USERNAME@$HOST2 "bash \"$REMOTE_SCRIPT_PATH\" \"$DEPLOY_PATH\" \"$JAR_FILENAME\" \"${{ secrets.DB_URL }}\" \"${{ secrets.DB_USERNAME }}\" \"${{ secrets.DB_PASSWORD }}\""
-        if [ $? -ne 0 ]; then echo "Error: Remote deploy script failed"; exit 1; fi
+        if [ $? -ne 0 ]; then echo "Error: Remote deploy script failed from host2"; exit 1; fi
         
         echo "--- DEPLOY JOB END ---"
