Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -161,7 +161,7 @@ jobs:
           fi
 
           mkdir -p $DEPLOY_PATH/logs
-          if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
+          # if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
 
           export DB_URL="$DB_URL"
           export DB_USERNAME="$DB_USERNAME"
@@ -174,6 +174,7 @@ jobs:
           echo "--- REMOTE SERVER: Verifying new application started successfully... ---"
           APP_STARTED=false
           for i in {1..3}; do # 5초 간격으로 3번 확인
+            sleep 5
             NEW_PID=$(pgrep -f "java -jar $CURRENT_SYMLINK")
             if [ -n "$NEW_PID" ]; then
               echo "--- REMOTE SERVER: New application process found (PID: $NEW_PID) after ($i*5) seconds. ---"
@@ -181,7 +182,6 @@ jobs:
               break
             fi
             echo "--- REMOTE SERVER: Waiting for new application to start... ($i/3) ---"
-            sleep 5
           done
 
           if [ "$APP_STARTED" = "false" ]; then
