Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -118,7 +118,8 @@ jobs:
           echo "--- REMOTE SERVER: Directory $NEW_RELEASE_DIR created. ---"
 
           echo "--- REMOTE SERVER: Moving JAR file from $DEPLOY_PATH/$JAR_FILENAME to $NEW_RELEASE_DIR/$JAR_FILENAME ---"
-          mv $DEPLOY_PATH/$JAR_FILENAME $NEW_RELEASE_DIR/$JAR_FILENAME
+          #mv $DEPLOY_PATH/$JAR_FILENAME $NEW_RELEASE_DIR/$JAR_FILENAME
+          cp $DEPLOY_PATH/$JAR_FILENAME $NEW_RELEASE_DIR/$JAR_FILENAME
           if [ $? -ne 0 ]; then echo "Error on server: Failed to move JAR file"; exit 1; fi
           echo "--- REMOTE SERVER: JAR file moved. ---"
 
@@ -160,7 +161,7 @@ jobs:
           fi
 
           mkdir -p $DEPLOY_PATH/logs
-          # if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
+          if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
 
           export DB_URL="$DB_URL"
           export DB_USERNAME="$DB_USERNAME"
@@ -175,7 +176,7 @@ jobs:
           for i in {1..3}; do # 5초 간격으로 3번 확인
             NEW_PID=$(pgrep -f "java -jar $CURRENT_SYMLINK")
             if [ -n "$NEW_PID" ]; then
-              echo "--- REMOTE SERVER: New application process found (PID: $NEW_PID) after $((i*5)) seconds. ---"
+              echo "--- REMOTE SERVER: New application process found (PID: $NEW_PID) after ($i*5) seconds. ---"
               APP_STARTED=true
               break
             fi
@@ -210,5 +211,4 @@ jobs:
             echo "--- REMOTE SERVER: No old releases found to delete or less than 5 releases. ---"
           fi
         EOF
-
         echo "--- DEPLOY JOB END ---"
