Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -158,8 +158,8 @@ jobs:
             echo "--- REMOTE SERVER: All old Java processes for $CURRENT_SYMLINK successfully terminated. ---"
           fi
 
-          mkdir -p "$DEPLOY_PATH/logs"
-          if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
+          mkdir -p $DEPLOY_PATH/logs
+          # if [ $? -ne 0 ]; then echo "Error on server: Failed to create log directory $DEPLOY_PATH/logs"; exit 1; fi
 
           export DB_URL="$DB_URL"
           export DB_USERNAME="$DB_USERNAME"
